steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/demo-service:latest",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/demo-service"
