name: "call demo service"
on:
  workflow_dispatch:

jobs:
  call_service:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.RUN_RUNNER }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: auth list
        shell: bash
        run: gcloud auth list

      - name: get service url
        shell: bash
        run: echo "RUN_URL=$(gcloud run services describe demo-service --region europe-west1 --format json | jq -r ".status.url")" >> "$GITHUB_ENV"

      - name: call service
        shell: bash
        run: |
          curl "$RUN_URL" -H "Authorization: Bearer $(gcloud auth print-identity-token)"
